// Autogenerated from Pigeon (v1.0.19), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by FLTNativeApi.
NSObject<FlutterMessageCodec> *FLTNativeApiGetCodec(void);

@protocol FLTNativeApi
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getPlatformVersionWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTNativeApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTNativeApi> *_Nullable api);

/// The codec used by FLTFlutterApi.
NSObject<FlutterMessageCodec> *FLTFlutterApiGetCodec(void);

@interface FLTFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)sessionInvalidWithCompletion:(void(^)(NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
