// Autogenerated from Pigeon (v1.0.19), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by FLTNativeApiInterface.
NSObject<FlutterMessageCodec> *FLTNativeApiInterfaceGetCodec(void);

@protocol FLTNativeApiInterface
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getPlatformVersionWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTNativeApiInterfaceSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTNativeApiInterface> *_Nullable api);

/// The codec used by FLTFlutterApiInterface.
NSObject<FlutterMessageCodec> *FLTFlutterApiInterfaceGetCodec(void);

@interface FLTFlutterApiInterface : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)sessionInvalidWithCompletion:(void(^)(NSError *_Nullable))completion;
@end
NS_ASSUME_NONNULL_END
